jogadores/urls.py
from django.urls import path

from . import views

app_name = 'jogadores'
urlpatterns = [
    path('', views.JogadorListView.as_view(), name='index'),  # edite esta linha
    path('create/', views.create_jogador, name='create'),
    path('<int:jogador_id>/', views.detail_jogador,
         name='detail'),
    path('update/<int:jogador_id>/', views.update_jogador, name='update'),
    path('delete/<int:jogador_id>/', views.delete_jogador, name='delete'),
    path('<int:jogador_id>/review/', views.create_comentario, name='review'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('lists/create', views.ListCreateView.as_view(), name='create-list'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('categoryFilter/<int:pk>', views.CategoryFilterView.as_view(), name='categoryFilter')
]

jogadorsite/urls.py
from django.contrib import admin
from django.urls import include, path
 
urlpatterns = [
    path('', include('staticpages.urls')),
    path('jogadores/', include('jogadores.urls')), # adicionar esta linha
    path('admin/', admin.site.urls),
]   

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), # adicione esta linha
    path('', views.index, name='index'),
]

jogadores/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Jogador(models.Model):
    name = models.CharField(max_length=255)
    poster_url = models.URLField(max_length=200, null=True)
    categories = models.ManyToManyField(Category)
    release_year = models.IntegerField( blank=True )
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.name}'

class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    jogador = models.ForeignKey(Jogador, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class List(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    jogadores = models.ManyToManyField(Jogador)

    def __str__(self):
        return f'{self.name} by {self.author}'

class Provider(models.Model):
    jogador = models.ForeignKey(Jogador, on_delete=models.CASCADE)
    service = models.CharField(max_length=255, blank=True)
    has_flat_price = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f'{self.service} @ {self.price if self.price else "flat"}'

staticpages/models.py
from django.db import models

# Create your models here.

jogadores/forms.py
from .models import Jogador, Review
from .models import Jogador, Review, Provider
from django.forms import ModelForm


class JogadorForm(ModelForm):
    class Meta:
        model = Jogador
        fields = [
            'name',
            'poster_url',
            'categories',
            'release_year',
        ]
        labels = {
            'name': 'Nome do Jogador',
            'poster_url': 'URL do Poster do Jogador',
            "categories": "categorias",
            'release_year': "Ano de aposentadoria"
        }


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

class ProviderForm(ModelForm):
    class Meta:
        model = Provider
        fields = [
        ]
        labels = {
        } 

jogadores/views.py
from django.shortcuts import render, get_object_or_404
# Create your views here.
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.urls import reverse, reverse_lazy
from .models import Jogador, Review, List, Provider, Category
from .forms import JogadorForm, ReviewForm, ProviderForm


class ListListView(generic.ListView):
    model = List
    template_name = 'jogadores/lists.html'


class ListCreateView(generic.CreateView):
    model = List
    template_name = 'jogadores/create_list.html'
    fields = ['name', 'author', 'jogadores']
    success_url = reverse_lazy('jogadores:lists')

class JogadorListView(generic.ListView):
    model = Jogador
    template_name = 'jogadores/index.html'

def list_jogadores(request):
    jogador_list = Jogador.objects.all()
    context = {'jogador_list': jogador_list}
    return render(request, 'jogadores/index.html', context)


def detail_jogador(request, jogador_id):
    jogador = get_object_or_404(Jogador, pk=jogador_id)
    context = {'jogador': jogador}
    return render(request, 'jogadores/detail.html', context)


def create_jogador(request):
    if request.method == 'POST':
        jogador_form = JogadorForm(request.POST)
        if jogador_form.is_valid():
            # Certifique-se de que o campo release_year está presente no formulário
            # Isso pode ser feito automaticamente se você estiver usando o ModelForm corretamente
            jogador = jogador_form.save(commit=False)

            # Certifique-se de que release_year está definido antes de salvar
            jogador.release_year = 2023  # Substitua isso pelo valor desejado

            jogador.save()
            # O método save_m2m() é usado para salvar os campos ManyToMany após salvar o objeto principal
            jogador_form.save_m2m()

            return HttpResponseRedirect(reverse('jogadores:detail', args=(jogador.pk,)))

    else:
        jogador_form = JogadorForm()

    context = {'jogador_form': jogador_form}
    return render(request, 'jogadores/create.html', context)

def update_jogador(request, jogador_id):
    jogador = get_object_or_404(Jogador, pk=jogador_id)

    if request.method == "POST":
        form = JogadorForm(request.POST)
        if form.is_valid():
            jogador.name = form.cleaned_data['name']
            jogador.poster_url = form.cleaned_data['poster_url']
            jogador.save()
            return HttpResponseRedirect(
                reverse('jogadores:detail', args=(jogador.id, )))
    else:
        form = JogadorForm(
            initial={
                'name': jogador.name,
                'poster_url': jogador.poster_url
            })

    context = {'jogador': jogador, 'form': form}
    return render(request, 'jogadores/update.html', context)

def delete_jogador(request, jogador_id):
    jogador = get_object_or_404(Jogador, pk=jogador_id)

    if request.method == "POST":
        jogador.delete()
        return HttpResponseRedirect(reverse('jogadores:index'))

    context = {'jogador': jogador}
    return render(request, 'jogadores/delete.html', context)

def create_comentario(request, jogador_id):
    jogador = get_object_or_404(Jogador, pk=jogador_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_author = form.cleaned_data['author']
            review_text = form.cleaned_data['text']
            review = Review(author=review_author,
                            text=review_text,
                            jogador=jogador)
            review.save()
            return HttpResponseRedirect(
                reverse('jogadores:detail', args=(jogador_id, )))
    else:
        form = ReviewForm()
    context = {'form': form, 'jogador': jogador}
    return render(request, 'jogadores/review.html', context)


class CategoryListView(generic.ListView):
    model = Category
    template_name = 'jogadores/categories.html'

class CategoryFilterView(generic.DetailView):
    model = Category
    template_name = 'jogadores/categoryFilter.html'

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)   

jogadores/templates/jogadores/categories.html
{% extends 'base.html' %} {% block content %}
<h2>Lendas do nosso futebol</h2>
{% if category_list %}
<section class="lista-de-cards">
    {% for category in category_list %}
    <article class="card">
        <p>
            <a  href = '{% url "jogadores:categoryFilter" category.id %}'> {{category.name}}</a>
        </p>
    </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma categoria.</p>
{% endif %} {% endblock content %}

jogadores/templates/jogadores/categoryFilter.html
{% extends 'base.html' %} {% block content %}
<h2>Lendas da categoria : {{category.name}}</h2>
{% if category.jogador_set.all%}
<section class="lista-de-cards">
    {% for jogador in category.jogador_set.all%}
    <article class="card">
      <a href="{% url 'jogadores:detail' jogador.id %}"> <!-- modifique esta linha -->
          <img src="{{ jogador.poster_url }}" alt="Poster do jogador {{ jogador.name }}" />
      </a>
      <p>{{ jogador.name }} </p>
    </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum jogador.</p>
{% endif %} {% endblock content %}

jogadores/templates/jogadores/create.html
{% extends 'base.html' %}

{% block title %}
Adicionar Jogadores
{% endblock title %}

{% block content %}
<h2>Adicionar Jogador</h2>

<form action="{% url 'jogadores:create' %}" method="post">
    {% csrf_token %}
    {{jogador_form.as_p }}
    {{ provider_form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

jogadores/templates/jogadores/create_list.html
{% extends 'base.html' %}

{% block title %}
Adicionar Jogador
{% endblock title %}

{% block content %}
<h2>Criar Lista de Jogadores</h2>

<form action="{% url 'jogadores:create-list' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

jogadores/templates/jogadores/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'jogadores:delete' jogador.id %}" method="post">
  {% csrf_token %}
  <p>
    Você tem certeza que deseja apagar o jogador "{{ jogador.name }}"?
  </p>
  <button type="submit">Apagar</button>
</form>
{% endblock content %}

jogadores/templates/jogadores/detail.html
{% extends 'base.html' %} 
{% block title %}
  {{ jogador.name }} 
{% endblock title %}
{% block content %}
<h2>Detalhes do  {{ jogador.name }} </h2>
<section class="dados-de-jogador">
  <img src="{{ jogador.poster_url }}" alt="Poster do jogador {{ jogador.name}}">
  <ul>
    <li>Nome: {{ jogador.name }}</li>
    {% if jogador.provider %}
        <li></li>
        {% if jogador.provider.has_flat_price %}
            <li> </li>
        {% else %}
            <li></li>
        {% endif %}
    {% endif %}
    {% if jogador.list_set.all %}
       <li>Incluso nas listas: {{ jogador.list_set.all|join:", " }} </li>
    {% endif %}



      {% if jogador.categories.all %}
        {% for category in jogador.categories.all%}
        <li> Conquista: {{category.name}} </li>
        {% endfor %}
      {% endif %}


      <li><a href="{% url 'jogadores:update' jogador.id %}">Editar</a></li>
      <li><a href="{% url 'jogadores:delete' jogador.id %}">Apagar</a></li>
      
  </ul>
  <a href="{% url 'jogadores:review' jogador.pk %}"><button>Crie Comentário</button></a>
</section>

<section>
  <header>
      <h3>Comentários</h3>
  </header>
  <ul>
      {% if jogador.review_set.all %}
          {% for review in jogador.review_set.all %}
              <figure>
                  <blockquote>
                      "{{ review.text }}"
                  </blockquote>
                  <figcaption>—{{ review.author }} em: {{ review.date }}    </figcaption>
              </figure>
          {% endfor %}
      {% else %}
          <p>Ainda não existe nenhum comentário para este jogador.</p>
      {% endif %}
  </ul>
</section>

{% endblock content %}

jogadores/templates/jogadores/index.html
{% extends 'base.html' %} {% block content %}
<h2>Lendas do nosso futebol</h2>
{% if jogador_list %}
<section class="lista-de-cards">
    {% for jogador in jogador_list %}
    <article class="card">
      <a href="{% url 'jogadores:detail' jogador.id %}"> <!-- modifique esta linha -->
          <img src="{{ jogador.poster_url }}" alt="Poster do jogador {{ jogador.name }}" />
      </a>
      <p>{{ jogador.name }} </p>
    </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum jogador.</p>
{% endif %} {% endblock content %}

jogadores/templates/jogadores/lists.html
{% extends 'base.html' %}

{% block title %}
Listas
{% endblock title %}

{% block content %}
<h2>Listas de Jogadores</h2>

<section>
    {% for list in list_list %}
    <hr>
    <article>
        <header>
            <h3>{{list.name}} (de {{ list.author }}) </h3>
        </header>
        <div class="lista-de-cards">
            {% for jogador in list.jogadores.all %}
            <div class="card">
                <a href="{% url 'jogadores:detail' jogador.id %}">
                    <img src="{{ jogador.poster_url }}" alt="Poster do jogador {{ jogador.name}}">
                </a>
                <p></p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'jogadores:create-list' %}"><button>Crie sua Lista</button></a>
</section>

{% endblock content %}

jogadores/templates/jogadores/review.html
{% extends 'base.html' %}

{% block content %}
<h2>Resenhar Jogador {{ jogador.name }} </h2>

<form action="{% url 'jogadores:review' jogador.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'jogadores:detail' jogador.id %}">Voltar para a página do jogador</a></p>
{% endblock content %}

jogadores/templates/jogadores/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Jogador {{ jogador.name }}</h2>
<form method="POST" action="{% url 'jogadores:update' jogador.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Watch that film!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a> <!-- adicione esta linha -->
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'jogadores:index' %}">Jogadores</a></li>
                <li><a href="{% url 'jogadores:lists' %}">Listas</a></li> <!-- adicionar esta linha -->
                <li><a href="{% url 'jogadores:create' %}">Adicione Jogadores</a></li> <!-- adicionar esta linha -->
                <li><a href="{% url 'about' %}">Sobre</a></li>
                <li><a href="{% url 'jogadores:categories' %}">Categorias</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}
{% load static %}

{%block style %}
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'single.css' %}">
{% endblock style %}

{% block title %}
Sobre mim
{% endblock title %}


{% block content %}
<div class="aboutMe">
    <p id="aboutMeText">Bem-vindo ao "Lendas do Futebol", o seu destino definitivo para explorar as carreiras extraordinárias de jogadores que deixaram uma marca indelével no mundo do futebol. Nesta plataforma, celebramos as conquistas, os momentos inesquecíveis e o legado duradouro dessas lendas do esporte mais amado do mundo.</p>
</div>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Conheça mais sobre lendas do futebol!</i></h1>
<p>A Página para você que ama futebol</p>
{% endblock content %}